config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers =>{:registrations => "user/registrations", :confirmations => "user/confirmations",:passwords => "user/passwords" }
  root 'welcome#index'
  get 'welcome/give_time', to: 'welcome#give_time'
  get 'overview/lavahound', to: 'overview#lavaHound'
  get 'confirmed' , to: 'welcome#confirmed'
  get 'unconfirmed', to: 'welcome#unconfirmed'
  get 'admin/pins', to: 'admin#pins'
  put 'admin/pins', to: 'admin#add_pins'
  get 'admin', to: 'admin#index'
  get 'download' , to: 'welcome#download'
  get '/ranking/uniques',   to: 'ranking#uniques'
  match '/users',   to: 'users#index',   via: 'get'
  match '/characters/:charname',     to: 'users#show',       via: 'get'
  match '/users/:username',     to: 'users#show_u',       via: 'get'
  #put 'users/:username' => 'users#unmark_spam', :as => 'unmark_spam'
  match '/news',   to: 'categories#index',   via: 'get'
  match '/news/:name',   to: 'categories#show',   via: 'get'
  put 'users/:username/mark_spam' => 'users#mark_spam', :as => 'mark_spam'
  put 'users/:username/be_seller' => 'users#be_seller', :as => 'be_seller'
  put 'users/:username/mark_supp' => 'users#mark_supp', :as => 'mark_supp'
  get 'search_users', to: 'users#search'
  get 'search_chars', to: 'users#search_char'
  get '/user/preferences' , to: 'users#preferences'
  put '/user/preferences' , to: 'users#withdraw_silk'
  get '/user/preferences/resetpassword' , to: 'users#send_reset_password_mail'
  get '/user/preferences/transfer_reward' , to: 'preferences#transfer_reward'
  get '/user/preferences/generate_code' , to: 'preferences#generate_code'
  get '/user/preferences/charge_code' , to: 'preferences#charge_code'
  put 'tickets/:id/close_ticket' => 'tickets#close_ticket', :as => 'close_ticket'

  match '/guilds/:guildname',     to: 'guild#activity',       via: 'get'
  match '/guilds/:guildname/members',     to: 'guild#members',       via: 'get'
  match '/guilds/:guildname/manage',     to: 'guild#manage',       via: 'get'
  put '/guilds/:guildname/manage', to: 'guild#update_guild'
  put '/guilds/:guildname', to: 'guild#post_activity'
  mount Attachinary::Engine => "/attachinary"
  resources :bugs, except: [:destroy,:edit,:update]
  resources :faq , except: [:show]
  resources :tickets do
    resources :tcomments
  end

  resources :articles do
    resources :comments

  end
  resources :categories ,  except: [:destroy, :index ,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<%= render 'layouts/adminNavbar' %>
<h1>This is the admin page </h1>
<%= link_to 'Home' , root_path %>
<%= link_to 'new article', new_article_path %>
<%= link_to 'All articles', articles_path %>
<%= link_to 'All users', users_path %>
<%= link_to 'All bug reports', bugs_path %>

<%= render 'users/search' %>



<%= render 'users/lookup' %>





</ul>

</li>

app/views/admin/pins.html.erb
<h1>This pins page</h1>
<%#= form_for @sellers do |f| %>

  <%#= f.collection_check_boxes :username, @sellers.all, :username, :name %>
  <%#= f.submit %>
<%# end %>

<%= form_tag @seller, method: :put, url: [@seller, :add_pins] do |f| %>
  <%= select_tag(:username, options_for_select( (@sellers.map {|seller| seller.username}) , params[:username] )) %>
  <%= text_field_tag :Npins, params[:Npins], placeholder:"Enter the amount of points", autofocus: true %>
  <%= button_tag  "Add Pins", type: :submit  %>
<% end %>