config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers =>{:registrations => "user/registrations", :confirmations => "user/confirmations",:passwords => "user/passwords" }
  root 'welcome#index'
  get 'welcome/give_time', to: 'welcome#give_time'
  get 'overview/lavahound', to: 'overview#lavaHound'
  get 'confirmed' , to: 'welcome#confirmed'
  get 'unconfirmed', to: 'welcome#unconfirmed'
  get 'admin/pins', to: 'admin#pins'
  put 'admin/pins', to: 'admin#add_pins'
  get 'admin', to: 'admin#index'
  get 'download' , to: 'welcome#download'
  get '/ranking/uniques',   to: 'ranking#uniques'
  match '/users',   to: 'users#index',   via: 'get'
  match '/characters/:charname',     to: 'users#show',       via: 'get'
  match '/users/:username',     to: 'users#show_u',       via: 'get'
  #put 'users/:username' => 'users#unmark_spam', :as => 'unmark_spam'
  match '/news',   to: 'categories#index',   via: 'get'
  match '/news/:name',   to: 'categories#show',   via: 'get'
  put 'users/:username/mark_spam' => 'users#mark_spam', :as => 'mark_spam'
  put 'users/:username/be_seller' => 'users#be_seller', :as => 'be_seller'
  put 'users/:username/mark_supp' => 'users#mark_supp', :as => 'mark_supp'
  get 'search_users', to: 'users#search'
  get 'search_chars', to: 'users#search_char'
  get '/user/preferences' , to: 'users#preferences'
  put '/user/preferences' , to: 'users#withdraw_silk'
  get '/user/preferences/resetpassword' , to: 'users#send_reset_password_mail'
  get '/user/preferences/transfer_reward' , to: 'preferences#transfer_reward'
  get '/user/preferences/generate_code' , to: 'preferences#generate_code'
  get '/user/preferences/charge_code' , to: 'preferences#charge_code'
  put 'tickets/:id/close_ticket' => 'tickets#close_ticket', :as => 'close_ticket'

  match '/guilds/:guildname',     to: 'guild#activity',       via: 'get'
  match '/guilds/:guildname/members',     to: 'guild#members',       via: 'get'
  match '/guilds/:guildname/manage',     to: 'guild#manage',       via: 'get'
  put '/guilds/:guildname/manage', to: 'guild#update_guild'
  put '/guilds/:guildname', to: 'guild#post_activity'
  mount Attachinary::Engine => "/attachinary"
  resources :bugs, except: [:destroy,:edit,:update]
  resources :faq , except: [:show]
  resources :tickets do
    resources :tcomments
  end

  resources :articles do
    resources :comments

  end
  resources :categories ,  except: [:destroy, :index ,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
require "SQL"
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user! , only: [:index,:unconfirmed , :confirmed, :give_time, :download]
  before_action :require_admin , only: [:admin, :pins]
  def index
      @a = Category.find_by_name("Announcements")
      @announcements = @a.articles.all.last(3).reverse

      @e= Category.find_by_name("Events")
      @events = @e.articles.all.last(3).reverse

      @m=Category.find_by_name("Maintenance")
      @maintenance = @m.articles.all.last(3).reverse

      @u= Category.find_by_name("Updates")
      @updates = @u.articles.all.last(3).reverse


    @DB= SQL.connect_shard
    @DBB = SQL.connect_shardlog
    uniqevent = @DBB[:_LogEventUnique].all.last(6).reverse

    @killers = []
    @uniques = []
    @dates = []
    uniqevent.each do |row|
      killer = @DB[:_Char].where(:charid => row[:charid])
      unique = @DB[:_RefObjUnique].where(:objectid => row[:objectid])
      @dates << row[:eventtime]

      if row[:killtype] == 0
        @killers << killer[:charname16]
      else
        @killers << killer[:nickname16]
      end
        @uniques << unique[:objectname128]
    end

   @onlineplayerscount = @DB[:_OnlinePlayerCount].all.last
   # @charid
   # @charname=
   # @uniquename= @lastkill[:ObjectName]
   # @killtime=

  end

  def give_time
    @time = Time.now.strftime("%H:%M:%S ")
    render :partial => 'shared/time_portion'
  end

  def confirmed
  end

  def unconfirmed
  end


  def download
    @a = Category.find_by_name("Announcements")
    @announcements = @a.articles.all.last(3)

  end

  private
  def require_admin



    if current_user.admin != true
      redirect_to root_path
    end
  end
  protected

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_Footer.html.erb
<!--=====================-->
<!--=        Footer       =-->
<!--================++=====-->
<footer id="footer-three" class="pr" data-bg-image="../assets/media/background/45.jpg">
  <div class="container">
    <div class="footer-inner">
      <div class="row">
        <div class="col-lg-3 col-sm-6 col-md-6">
          <div class="footer-about">
            <div class="content">
              <p>
                Z Online is a fantasy MMORPG set in the 7th century AD, along the Silk Road between China and Europe. The game requires no periodic subscription fee, but players can purchase cosmetic items to have a cool look.
              </p>
            </div>

            <ul class="footer-social-link">
              <li class="fb-bg"><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li class="in-bg"><a href="#"><i class="fa fa-youtube"></i></a></li>
              <li class="tw-bg"><a href="#"><i class="fab fa-discord"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- /.col-lg-3 col-sm-6 col-md-6 -->

        <div class="col-lg-3 col-sm-6 col-md-6">
          <div class="footer-menu-inner">
            <a  href="https://www.elitepvpers.com"><img src="https://chimpeon.com/images/elitepvpers_logo.png"></a>
          </div>
        </div>
        <!-- /.col-lg-3 col-sm-6 col-md-6 -->

        <div class="col-lg-3 col-sm-6 col-md-6">
        </div>
        <!-- /.col-lg-3 col-sm-6 col-md-6 -->

        <div class="col-lg-3 col-sm-6 col-md-6">
        </div>
        <!-- /.col-lg-3 col-sm-6 col-md-6 -->
      </div>
      <!-- /.row -->

      <div class="copy-right">
        <p>Copyright 2018 <a href="www.z-sro.com" >Z Team</a> All Rights Reserved</p>
      </div>
    </div>
    <!-- /.footer-inner -->
  </div>
  <!-- /.container -->
</footer>
<!-- /#footer-three -->

app/views/welcome/_Navbar.html.erb
<!--=========================-->
<!--=        Navbar         =-->
<!--=========================-->
<header id="header" class="header-one">
  <div class="top-menu">
    <div class="container">
      <div class="top-menu-wrap">
        <div class="row">
          <div class="col-md-8">
            <div class="top-menu-left">
              <ul class="head-social-link">
                <li><a href="https://www.facebook.com/ZOnline2018" target="_blank"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="https://discord.gg/cbpJ7fJ" target="_blank"><i class="fab fa-discord"></i></a></li>
              </ul>
              <!-- /.head-social-link -->
            </div>
            <!-- /.top-menu-left -->


            <div class="header-text">
              <span class="tour-title">Announcements</span>
              <h4 class="ah-headline">
                 <span class="ah-words-wrapper">
                     <% @announcements.each do |article| %>
                       <% if @announcements.first == article %>
                        <b class="is-visible"><%= article.title %></b>
                       <% else %>
                        <b><%= article.title %></b>
                       <% end %>
                     <% end %>
                 </span>
              </h4>
            </div>
          </div>
          <!-- /.col-md-6 -->

          <div class="col-md-4">
            <% if user_signed_in? %>
              <ul class="user-link nav justify-content-end">
                <%#= link_to , users_path(@current_user), "test<span>*</span>".html_safe %>
                <li><a href="<%= user_preferences_path %>"><i class="fa fa-user"></i> <%= current_user.name %></a></li>

                <% if current_user.seller? %>
                  <li><a href="#"><i class="fa  fa-usd"></i> <%= current_user.pins %></a></li>
                <% end %>

                <li>
                  <%= link_to destroy_user_session_path, :method => :delete  do %>
                  <i class="fa fa-sign-in"></i>logout
                  <% end %>
                </li>
              </ul>

            <% else %>
              <ul class="user-link nav justify-content-end">
                <li><a href="../users/sign_in"><i class="fa fa-user"></i>Login</a></li>
                <li><a href="../users/sign_up"><i class="fa fa-sign-in"></i>Sign Up</a></li>
              </ul>
            <% end %>

            <!-- /.user-link -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.top-menu-wrap -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.top-menu -->

  <div class="nav" style="height: 130px;">
    <div class="container">
      <div class="nav-wrap">
        <div id="site-logo">
          <a href="">
            <img src="../assets/img/logo.png" alt="Site Logo">
          </a>
        </div>
        <ul class="tim-nav text-right">

          <li class="menu-item">
            <a href="/">
              Home
              <span class="dot"></span>
            </a>
          </li>

          <li class="menu-item-has-children">

            <a href="#">
              News
              <span class="dot"></span>
            </a>

            <ul class="sub-menu">
              <li><a href="../news/Announcements" >Announcements</a></li>
              <li><a href="../news/Events" >Events</a></li>
              <li><a href="../news/Maintenance" >Maintenance</a></li>
              <li><a href="../news/Updates" >Updates</a></li>
            </ul>

          </li>

          <li class="menu-item">
            <a href="../download" >
              Download
              <span class="dot"></span>
            </a>
          </li>

          <li class="menu-item-has-children">
            <a href="#">
              Rankings
              <span class="dot"></span>
            </a>
            <div class="mega-menu-inner">
              <div class="tab">

                <div class="tab_content">


                    <div class="row">

                      <div class="col-md-3">
                        <div class="top-team text-center">
                          <a href="../ranking/uniques" ><img src="../assets/media/team/1.jpg" alt="team"></a>
                          <h3 class="game-team-name"><a href="../ranking/uniques">Unique Ranking</a>
                          </h3>
                        </div>
                        <!-- /.top-team -->
                      </div>

                      <div class="col-md-3">
                        <div class="top-team text-center">
                          <a href="#"><img src="../assets/media/team/2.jpg" alt="team"></a>
                          <h3 class="game-team-name"><a href="#">Gems author</a>
                          </h3>
                        </div>
                        <!-- /.top-team -->
                      </div>

                      <div class="col-md-3">
                        <div class="top-team text-center">
                          <a href="#"><img src="../assets/media/team/3.jpg" alt="team"></a>
                          <h3 class="game-team-name text-center"><a href="#">Hard Gamer</a>
                          </h3>
                        </div>
                        <!-- /.top-team -->
                      </div>

                      <div class="col-md-3">
                        <div class="top-team text-center">
                          <a href="#"><img src="../assets/media/team/4.jpg" alt="team"></a>
                          <h3 class="game-team-name"><a href="#">Speed Controller</a>
                          </h3>
                        </div>
                        <!-- /.top-team -->
                      </div>

                    </div>
                    <!-- /.row -->
                  </div>
                  <!-- / tabs_item -->

                </div>
                <!-- / tab_content -->
              </div>
              <!-- / tab -->
            <!-- /.mega-menu-inner -->
          </li>

          <li class="menu-item-has-children">
            <a href="#">
              Support
              <span class="dot"></span>
            </a>

            <ul class="sub-menu text-center" style="font-size: 32px;">
              <li><a href="../tickets/new">Submit Ticket</a></li>
              <li><a href="../bugs/new">Report Bug</a></li>
              <li><a href="../faq">FAQ</a></li>
<!--              <li><a href="news/Updates">Updates</a></li>-->
            </ul>

          </li>

          <li class="nav-item search-btn">
            <i class="fa fa-search"></i>
          </li>

        </ul>
        <div class="top-search-form">
          <%= render "users/searchchar" %>
        </div>
      </div>
      <!-- /.nav-wrap -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.nav -->
</header>
<!-- /#header -->

<!--================================-->
<!--=        Mobile Navbar         =-->
<!--================================-->
<header id="mobile-nav-wrap">
  <div class="mob-header-inner d-flex justify-content-between">
    <div id="mobile-logo" class="d-flex justify-content-start">
      <a href="#"><img src="../assets/img/logo.png" alt="Site Logo"></a>
    </div>

    <% if user_signed_in? %>
      <ul class="user-link nav justify-content-end">
        <%#= link_to , users_path(@current_user), "test<span>*</span>".html_safe %>
        <li><a href="#"><i class="fa fa-user"></i> <%= current_user.username %></a></li>

        <% if current_user.seller? %>
          <li><a href="#"><i class="fas fa-dollar-sign"></i> <%= current_user.pins %></a></li>
        <% end %>

        <li>
          <%= link_to destroy_user_session_path, :method => :delete  do %>
            <i class="fa fa-sign-in"></i>logout
          <% end %>
        </li>

      </ul>

    <% else %>
      <ul class="user-link nav justify-content-end">
        <li><a href="../users/sign_in"><i class="fa fa-user"></i>Login</a></li>
        <li><a href="../users/sign_up"><i class="fa fa-sign-in"></i>Sign Up</a></li>
      </ul>
    <% end %>


    <div id="nav-toggle" class="nav-toggle hidden-md">
      <div class="toggle-inner">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- /.mob-header-inner -->
</header>
<!-- /#mobile-header -->

<div class="mobile-menu-inner">

  <div class="close-menu">
    <span class="bar"></span>
    <span class="bar"></span>
  </div>

  <nav id="accordian">
    <ul class="accordion-menu">
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="#0" class="dropdownlink">News</a>
        <ul class="submenuItems">
          <li><a href="../news/Announcements">Announcements</a></li>
          <li><a href="../news/Events">Events</a></li>
          <li><a href="../news/Maintenance">Maintenance</a></li>
          <li><a href="../news/Updates">Updates</a></li>
        </ul>
      </li>
      <li>
        <a href="../download" >Download</a>
      </li>

      <li>
        <a href="#0" class="dropdownlink">Rankings</a>
        <ul class="submenuItems">
          <li><a href="../ranking/uniques">Uniques</a></li>
          <li><a href="../news/Events">2</a></li>
          <li><a href="../news/Maintenance">3</a></li>
          <li><a href="../news/Updates">4</a></li>
        </ul>
      </li>

      <li>
        <a href="#0" class="dropdownlink">Support</a>
        <ul class="submenuItems">
          <li><a href="../tickets/new">Submit Ticket</a></li>
          <li><a href="../bugs/new">Report Bug</a></li>
          <li><a href="../faq">FAQ</a></li>
        </ul>
      </li>

    </ul>
  </nav>

  <form action="#" id="moble-search">
    <input type="text" placeholder="Search for character ....">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <!-- /#moble-search -->

  <ul class="footer-social-link">
    <li class="fb-bg"><a href="#"><i class="fa fa-facebook"></i></a></li>
    <li class="in-bg"><a href="#"><i class="fa fa-youtube"></i></a></li>
    <li class="tw-bg"><a href="#"><i class="fab fa-discord"></i></a></li>
  </ul>
</div>
<!-- /.mobile-menu-inner -->

app/views/welcome/_head.html.erb
<head>
  <%= javascript_include_tag "validation.js" %>


  <!-- Fav Icon -->
  <link rel="apple-touch-icon" sizes="180x180" href="assets/img/fav-icons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/img/fav-icons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/img/fav-icons/favicon-16x16.png">
  <meta name="theme-color" content="#3d0e03">

  <!-- Dependency Styles -->
  <link rel="stylesheet" href="assets/dependencies/bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="assets/dependencies/font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/brands.css" integrity="sha384-7xAnn7Zm3QC1jFjVc1A6v/toepoG3JXboQYzbM0jrPzou9OFXm/fY6Z/XiIebl/k" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">




  <!-- Site Stylesheet -->
  <link rel="stylesheet" href="assets/dependencies/swiper/swiper.min.css" type="text/css">
  <link rel="stylesheet" href="assets/dependencies/wow/css/animate.css" type="text/css">
  <link rel="stylesheet" href="assets/dependencies/magnific-popup/magnific-popup.css" type="text/css">
  <link rel="stylesheet" href="assets/dependencies/jquery-animated-headlines/css/jquery.animatedheadline.css" type="text/css">
  <link rel="stylesheet" href="assets/home-dependencies/woocommerce.css" type="text/css">
  <link rel="stylesheet" href="assets/dependencies/jquery-ui/css/jquery-ui.css" type="text/css">
  <link rel="stylesheet" href="assets/home-dependencies/app.css" type="text/css">

  <!-- Google Web Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Khand:300,400,500,600,700%7C;Source+Sans+Pro:200,300,400,600,600i,700,900" rel="stylesheet">

</head>

app/views/welcome/admin.html.erb
<%= render 'layouts/adminNavbar' %>
<h1>This is the admin page </h1>
<%= link_to 'Home' , root_path %>
<%= link_to 'new article', new_article_path %>
<%= link_to 'All articles', articles_path %>
<%= link_to 'All users', users_path %>

<%= render 'users/search' %>

app/views/welcome/confirmed.html.erb
<!DOCTYPE html>
<html lang="en" class="Gibbu_@hotmail.com">

<head>
  <meta charset="UTF-8">
  <title> Z Online | Congratulation ! </title>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.transit/0.9.12/jquery.transit.js" integrity="sha256-mkdmXjMvBcpAyyFNCVdbwg4v+ycJho65QLDwVE3ViDs=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">


  <%= stylesheet_link_tag "login.css" %>


</head>

<body>


<!-- NORMALIZED CSS INSTALLED-->
<!-- View settings for more info.-->
<div id="container" >
  <div id="inviteContainer"  style="width: 80%; height: auto">
    <div class="logoContainer" style="width: 100%; height: auto">
      <img class="logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Approve_icon.svg/2000px-Approve_icon.svg.png"/>
      <img class="text" src="https://image.ibb.co/gzYfu8/cooltext292378671326620.png" style="width: 30%; height: auto;"/>
      <img class="text" src="https://preview.ibb.co/hjrTgo/cooltext292378802949702.png" style="width: 50%; height: auto;"/>
      <button class="acceptBtn text" style="z-index: 155; margin-top: 2%; font-size: 28px; font-weight: 700;" onclick="location.href='../users/sign_in';">Login</button>
    </div>
  </div>
</div>


<%= javascript_include_tag "login.js"  %>




</body>

</html>

app/views/welcome/download.html.erb
<!doctype html>

<html>


<head>
  <%= javascript_include_tag "validation.js" %>

  <!-- Meta Data -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> Z Online | Download </title>

  <!-- Fav Icon -->
  <link rel="apple-touch-icon" sizes="180x180" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="32x32" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="16x16" href="../assets/media/Z_ICO.ico">
  <meta name="theme-color" content="#3d0e03">

  <!-- Dependency Styles -->
  <link rel="stylesheet" href="../assets/dependencies/bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/brands.css" integrity="sha384-7xAnn7Zm3QC1jFjVc1A6v/toepoG3JXboQYzbM0jrPzou9OFXm/fY6Z/XiIebl/k" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">


  <!-- Site Stylesheet -->
  <link rel="stylesheet" href="../assets/dependencies/swiper/swiper.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/wow/css/animate.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/magnific-popup/magnific-popup.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-animated-headlines/css/jquery.animatedheadline.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/woocommerce.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-ui/css/jquery-ui.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/app.css" type="text/css">

  <!-- Google Web Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Khand:300,400,500,600,700%7C;Source+Sans+Pro:200,300,400,600,600i,700,900" rel="stylesheet">


</head>

<body class="blog-grid-four" data-bg-image="../assets/media/blog/57.jpg" data-style="default">
<!--
<div id="loader-wrapper">
<div class="loader">
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
<span></span>
</div>
</div> -->
<div id="loader-wrapper">
  <div class='loader'></div>
</div>

<div class="switch-top">
  <p>Back To Top</p>
  <a href="#main_content" data-type="section-switch" class="return-to-top">
    <i class="fa fa-angle-double-up"></i>
  </a>
</div>

<div id="main_content">

  <%= render 'welcome/Navbar' %>

  <!--=========================-->
  <!--=        Banner         =-->
  <!--=========================-->
<!--  <section id="page-header" data-bg-image="../assets/media/background/halfz6.jpg" style="background-color: black;max-height: 200px">-->
<!--    <div class="container">-->
<!--      <div class="page-title-wrap">-->
<!--        <div class="page-title-inner">-->
<!--          <h1>Game Download</h1>-->
<!--          <span class="delemitter" data-bg-image="../assets/media/banner/s1.png"></span>-->
<!--        </div>-->
<!--        <!-- /.page-title-inner -->
<!--      </div>-->
<!--      <!-- /.page-title-wrap -->
<!--    </div>-->
    <!-- /.container -->
<!--  </section>-->
  <!-- /#page-header -->


  <!--============================================-->
  <!--=        Game Download Zoombie Two         =-->
  <!--============================================-->
  <section id="game-download-three" class="section-padding" data-parallax="image" data-bg-image="../assets/media/background/z3.jpg">
    <div class="container">
      <div style="padding-top: 15%;"></div>
      <div class="download-inner d-inner-two text-center">
        <h2 class="title">
          <strong style= "color: #f68b1f ">Z</strong> Online<br>
          <span>Play it, Love it</span>
        </h2>

        <h3 style="line-height: 2">
          Enjoy the new era of MMORPG, We are offering a great, new, and awesome experience you will ever had.
          above that <strong> It's FREE TO PLAY </strong>
        </h3>

        <div id="D-btn" style="width: 50%;">
          <div id="border1">
            <div id="ornaments">
              <div id="moreornaments">
                <div id="radialgradient">
                  <div id="gloss">
                    <div id="inner">
                      <i class="fa fa-cloud-download"></i>
                      Download Now
                    </div>
                    <div id="gradientbottom"></div>
                  </div>
                </div>
                <div class="triangle top left bg"></div>
                <div class="triangle middle left bg"></div>
                <div class="triangle middle left"></div>
                <div class="triangle top left"></div>
                <div class="triangle bottom left bg"></div>
                <div class="triangle bottom left"></div>
                <div class="triangle top right bg"></div>
                <div class="triangle top right"></div>
                <div class="triangle middle right bg"></div>
                <div class="triangle middle right"></div>
                <div class="triangle bottom right bg"></div>
                <div class="triangle bottom right"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.container -->
  </section>
  <!-- /#game-download-three -->
  <%= render 'welcome/Footer' %>
</div>
<!-- /#site -->

<!-- Dependency Scripts -->
<script src="../assets/dependencies/jquery/jquery.min.js"></script>
<script src="../assets/dependencies/bootstrap/js/bootstrap.min.js"></script>
<script src="../assets/dependencies/swiper/js/swiper.min.js"></script>
<script src="../assets/dependencies/swiperRunner/swiperRunner.min.js"></script>
<script src="../assets/dependencies/magnific-popup/js/jquery.magnific-popup.min.js"></script>
<script src="../assets/dependencies/jquery-ui/jquery-ui.min.js"></script>
<script src="../assets/dependencies/jquery-animated-headlines/js/jquery.animatedheadline.min.js"></script>
<script src="../assets/dependencies/jquery.countdown/jquery.countdown.min.js"></script>
<script src="../assets/dependencies/countUp.js/js/countUp.min.js"></script>
<script src="../assets/dependencies/jquery.appear.bas2k/jquery.appear.js"></script>
<script src="../assets/dependencies/jquery.ripples/jquery.ripples.js"></script>
<script src="../assets/dependencies/wow/js/wow.min.js"></script>

<!-- Site Scripts -->
<script src="../assets/home-dependencies/app.js"></script>


</body>


<!-- Mirrored from themeim.com/demo/gameisland/download.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Jun 2018 07:51:03 GMT -->
</html>