config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers =>{:registrations => "user/registrations", :confirmations => "user/confirmations",:passwords => "user/passwords" }
  root 'welcome#index'
  get 'welcome/give_time', to: 'welcome#give_time'
  get 'overview/lavahound', to: 'overview#lavaHound'
  get 'confirmed' , to: 'welcome#confirmed'
  get 'unconfirmed', to: 'welcome#unconfirmed'
  get 'admin/pins', to: 'admin#pins'
  put 'admin/pins', to: 'admin#add_pins'
  get 'admin', to: 'admin#index'
  get 'download' , to: 'welcome#download'
  get '/ranking/uniques',   to: 'ranking#uniques'
  match '/users',   to: 'users#index',   via: 'get'
  match '/characters/:charname',     to: 'users#show',       via: 'get'
  match '/users/:username',     to: 'users#show_u',       via: 'get'
  #put 'users/:username' => 'users#unmark_spam', :as => 'unmark_spam'
  match '/news',   to: 'categories#index',   via: 'get'
  match '/news/:name',   to: 'categories#show',   via: 'get'
  put 'users/:username/mark_spam' => 'users#mark_spam', :as => 'mark_spam'
  put 'users/:username/be_seller' => 'users#be_seller', :as => 'be_seller'
  put 'users/:username/mark_supp' => 'users#mark_supp', :as => 'mark_supp'
  get 'search_users', to: 'users#search'
  get 'search_chars', to: 'users#search_char'
  get '/user/preferences' , to: 'users#preferences'
  put '/user/preferences' , to: 'users#withdraw_silk'
  get '/user/preferences/resetpassword' , to: 'users#send_reset_password_mail'
  get '/user/preferences/transfer_reward' , to: 'preferences#transfer_reward'
  get '/user/preferences/generate_code' , to: 'preferences#generate_code'
  get '/user/preferences/charge_code' , to: 'preferences#charge_code'
  put 'tickets/:id/close_ticket' => 'tickets#close_ticket', :as => 'close_ticket'

  match '/guilds/:guildname',     to: 'guild#activity',       via: 'get'
  match '/guilds/:guildname/members',     to: 'guild#members',       via: 'get'
  match '/guilds/:guildname/manage',     to: 'guild#manage',       via: 'get'
  put '/guilds/:guildname/manage', to: 'guild#update_guild'
  put '/guilds/:guildname', to: 'guild#post_activity'
  mount Attachinary::Engine => "/attachinary"
  resources :bugs, except: [:destroy,:edit,:update]
  resources :faq , except: [:show]
  resources :tickets do
    resources :tcomments
  end

  resources :articles do
    resources :comments

  end
  resources :categories ,  except: [:destroy, :index ,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :user
  validates :question , presence: true
  validates :answer , presence: true
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  before_action :set_faq , only: [:edit , :update,:destroy]
  before_action :require_admin, only: [:update,:edit,:new,:create,:destroy]
  def index
    @faqs = Faq.order('updated_at DESC').paginate(page: params[:page], per_page: 5)
  end


  def new
    @faq = Faq.new
  end
  def edit

  end
  def create

    @faq = Faq.new(faq_params)
    @faq.user = current_user

    if @faq.save
      flash[:notice] = "your question was successfully posted"
      redirect_to faq_index_path
    else
      render 'new'
    end
  end
  def update

    if @faq.update(faq_params)
      flash[:notice]= "question was successfully updated"
      redirect_to faq_index_path
    else
      render 'edit'
    end
  end
  def destroy
    @faq.destroy
    flash[:danger]= "question was successfully deleted"
    redirect_to faq_index_path
  end




  private
  def set_faq
    @faq = Faq.find(params[:id])
  end

  def faq_params

    params.require(:faq).permit(:question, :answer)

  end
  def require_admin
    if current_user.admin != true
      flash[:danger]="You can read FAQ only!!"
      redirect_to root_path
    end
  end
end

app/views/faq/_faq.html.erb
<% obj.each do |faq|%>
  <div class = "row">
    <div class = "col-xs-8 col-xs-offset-2">
      <div class="well well-lg">


        <div class="article-body">
          <%= faq.question %>
          <div class="article-body">
            <%= faq.answer %>
          </div>
        </div>
        <% if current_user.admin? %>
          <div class="article-actions">
            <%= link_to "Edit this question" , edit_faq_path(faq),class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this question", faq_path(faq),
                        method: :delete, data: {confirm: "Are you sure you want to delete the question?"},
                        class: "btn btn-xs btn-danger"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/faq/_form.html.erb
<%= render 'shared/errors', obj: @faq %>

<%= form_for(@faq, url: faq_index_path,:html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">

    <div class="control-label col-sm-2">

      <%= f.label :question %>

    </div>

    <div class="col-sm-8">

      <%= f.text_area :question, rows: 10, class: "form-control", placeholder: "question" %>

    </div>

  </div>
  <div class="form-group">

    <div class="control-label col-sm-2">

      <%= f.label :answer %>

    </div>

    <div class="col-sm-8">

      <%= f.text_area :answer, rows: 10, class: "form-control", placeholder: "answer for the question" %>

    </div>

  </div>

  <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">

      <%= f.submit class: 'btn btn-primary btn-lg' %>

    </div>

  </div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

  [ <%= link_to "Cancel request and return to articles listing", faq_index_path %> ]

</div>

app/views/faq/edit.html.erb
<h1>Edit existing a frequently asked question and its answer</h1>
<%= render 'shared/errors', obj: @faq %>

<%= form_for(@faq,:html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">

    <div class="control-label col-sm-2">

      <%= f.label :question %>

    </div>

    <div class="col-sm-8">

      <%= f.text_area :question, rows: 10, class: "form-control", placeholder: "question" %>

    </div>

  </div>
  <div class="form-group">

    <div class="control-label col-sm-2">

      <%= f.label :answer %>

    </div>

    <div class="col-sm-8">

      <%= f.text_area :answer, rows: 10, class: "form-control", placeholder: "answer for the question" %>

    </div>

  </div>

  <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">

      <%= f.submit class: 'btn btn-primary btn-lg' %>

    </div>

  </div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

  [ <%= link_to "Cancel request and return to articles listing", faq_index_path %> ]

</div>

app/views/faq/index.html.erb
<%#= render 'layouts/adminNavbar'%>

<!--<h1 align = "center">Listing all requently asked question and its answer</h1>-->
<%# if current_user.admin? %>
  <%#= link_to "new FAQ", new_faq_path %>
<%# end %>
<!--<div align="center">-->
  <%#= will_paginate @faqs %>
<!--</div>-->
<%#= render 'faq', obj: @faqs%>
<!--<div align="center">-->
  <%#= will_paginate @faqs %>
<!--</div>-->
<!doctype html>

<html>


<!-- Mirrored from themeim.com/demo/gameisland/accordion-tab.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Jun 2018 07:51:03 GMT -->
<head>
  <%= javascript_include_tag "validation.js" %>

  <!-- Meta Data -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> Z Online | FAQ </title>

  <!-- Fav Icon -->
  <link rel="apple-touch-icon" sizes="180x180" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="32x32" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="16x16" href="../assets/media/Z_ICO.ico">
  <meta name="theme-color" content="#3d0e03">

  <!-- Dependency Styles -->
  <link rel="stylesheet" href="../assets/dependencies/bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/brands.css" integrity="sha384-7xAnn7Zm3QC1jFjVc1A6v/toepoG3JXboQYzbM0jrPzou9OFXm/fY6Z/XiIebl/k" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">


  <!-- Site Stylesheet -->
  <link rel="stylesheet" href="../assets/dependencies/swiper/swiper.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/wow/css/animate.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/magnific-popup/magnific-popup.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-animated-headlines/css/jquery.animatedheadline.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/woocommerce.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-ui/css/jquery-ui.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/app.css" type="text/css">

  <!-- Google Web Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Khand:300,400,500,600,700%7C;Source+Sans+Pro:200,300,400,600,600i,700,900" rel="stylesheet">

</head>

<body class="bgb" data-style="default">
<div id="loader-wrapper">
  <div class='loader'></div>
</div>

<div class="switch-top">
  <p>Back To Top</p>
  <a href="#main_content" data-type="section-switch" class="return-to-top">
    <i class="fa fa-angle-double-up"></i>
  </a>
</div>

<div id="main_content">

  <%= render "welcome/Navbar" %>

  <!--=========================-->
  <!--=        Banner         =-->
  <!--=========================-->
  <!--  <section id="page-header" data-bg-image="../assets/media/background/halfz6.jpg" style="background-color: black;max-height: 200px">-->
  <!--    <div class="container">-->
  <!--      <div class="page-title-wrap">-->
  <!--        <div class="page-title-inner">-->
  <!--          <h1>Submit Ticket</h1>-->
  <!--          <span class="delemitter" data-bg-image="../assets/media/banner/s1.png"></span>-->
  <!--        </div>-->
  <!--         /.page-title-inner -->
  <!--      </div>-->
  <!--       /.page-title-wrap -->
  <!--    </div>-->
  <!-- /.container -->
  <!--  </section>-->
  <!-- /#page-header -->


  <!--========================================-->
  <!--=        Blog Grid Four Column         =-->
  <!--========================================-->
  <section id="faq" data-bg-image="../assets/media/ticket/faq.png" style="min-height: 700px;">
    <div class="container">
      <div style="padding-top: 20%;"></div>
      <div class="row">
        <div class="col-md-12">
          <div class="faq">
            <div class="panel-group" id="accordion-two">
              <% @faqs.each do |faq| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <div class="panel-title"><a data-toggle="collapse" class="panel-toggle" data-parent="#accordion-two" href="#collapse<%= faq.id %>"><%= faq.question %></a></div>
                  </div>
                  <div id="collapse<%= faq.id %>" class="panel-collapse collapse">
                    <div class="panel-body"> <%= faq.answer %></div>
                  </div>
                </div>
            <% end %>
            </div>
          </div>
          <!-- /.choose -->
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </section>
  <!-- /.style-one -->
  <%= render "welcome/Footer" %>

</div>
<!-- /#site -->

<!-- Dependency Scripts -->
<script src="../assets/dependencies/jquery/jquery.min.js"></script>
<script src="../assets/dependencies/bootstrap/js/bootstrap.min.js"></script>
<script src="../assets/dependencies/swiper/js/swiper.min.js"></script>
<script src="../assets/dependencies/swiperRunner/swiperRunner.min.js"></script>
<script src="../assets/dependencies/magnific-popup/js/jquery.magnific-popup.min.js"></script>
<script src="../assets/dependencies/jquery-ui/jquery-ui.min.js"></script>
<script src="../assets/dependencies/jquery-animated-headlines/js/jquery.animatedheadline.min.js"></script>
<script src="../assets/dependencies/jquery.countdown/jquery.countdown.min.js"></script>
<script src="../assets/dependencies/countUp.js/js/countUp.min.js"></script>
<script src="../assets/dependencies/jquery.appear.bas2k/jquery.appear.js"></script>
<script src="../assets/dependencies/jquery.ripples/jquery.ripples.js"></script>
<script src="../assets/dependencies/wow/js/wow.min.js"></script>

<!-- Site Scripts -->
<script src="../assets/home-dependencies/app.js"></script>

</body>


<!-- Mirrored from themeim.com/demo/gameisland/accordion-tab.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Jun 2018 07:51:03 GMT -->
</html>

app/views/faq/new.html.erb
<h1>Create a frequently asked question and its answer</h1>

<%= render 'form'%>