config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers =>{:registrations => "user/registrations", :confirmations => "user/confirmations",:passwords => "user/passwords" }
  root 'welcome#index'
  get 'welcome/give_time', to: 'welcome#give_time'
  get 'overview/lavahound', to: 'overview#lavaHound'
  get 'confirmed' , to: 'welcome#confirmed'
  get 'unconfirmed', to: 'welcome#unconfirmed'
  get 'admin/pins', to: 'admin#pins'
  put 'admin/pins', to: 'admin#add_pins'
  get 'admin', to: 'admin#index'
  get 'download' , to: 'welcome#download'
  get '/ranking/uniques',   to: 'ranking#uniques'
  match '/users',   to: 'users#index',   via: 'get'
  match '/characters/:charname',     to: 'users#show',       via: 'get'
  match '/users/:username',     to: 'users#show_u',       via: 'get'
  #put 'users/:username' => 'users#unmark_spam', :as => 'unmark_spam'
  match '/news',   to: 'categories#index',   via: 'get'
  match '/news/:name',   to: 'categories#show',   via: 'get'
  put 'users/:username/mark_spam' => 'users#mark_spam', :as => 'mark_spam'
  put 'users/:username/be_seller' => 'users#be_seller', :as => 'be_seller'
  put 'users/:username/mark_supp' => 'users#mark_supp', :as => 'mark_supp'
  get 'search_users', to: 'users#search'
  get 'search_chars', to: 'users#search_char'
  get '/user/preferences' , to: 'users#preferences'
  put '/user/preferences' , to: 'users#withdraw_silk'
  get '/user/preferences/resetpassword' , to: 'users#send_reset_password_mail'
  get '/user/preferences/transfer_reward' , to: 'preferences#transfer_reward'
  get '/user/preferences/generate_code' , to: 'preferences#generate_code'
  get '/user/preferences/charge_code' , to: 'preferences#charge_code'
  put 'tickets/:id/close_ticket' => 'tickets#close_ticket', :as => 'close_ticket'

  match '/guilds/:guildname',     to: 'guild#activity',       via: 'get'
  match '/guilds/:guildname/members',     to: 'guild#members',       via: 'get'
  match '/guilds/:guildname/manage',     to: 'guild#manage',       via: 'get'
  put '/guilds/:guildname/manage', to: 'guild#update_guild'
  put '/guilds/:guildname', to: 'guild#post_activity'
  mount Attachinary::Engine => "/attachinary"
  resources :bugs, except: [:destroy,:edit,:update]
  resources :faq , except: [:show]
  resources :tickets do
    resources :tcomments
  end

  resources :articles do
    resources :comments

  end
  resources :categories ,  except: [:destroy, :index ,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories

  has_many :articles, through: :article_categories

validates :name , presence: true,length: {minimum: 3, maximum: 30}
  validates_uniqueness_of :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin , except: [:index,:show]

  def index

    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new

    @category = Category.new

  end

  def create

    @category = Category.new(category_params)

    if @category.save

      flash[:success] = "Category was created successfully"

      redirect_to '/news'

    else

      render 'new'

    end

  end
  def show

    @a = Category.find_by_name("Announcements")
    @announcements = @a.articles.all.last(3)

    @category = Category.find_by_name(params[:name])

    @category_articles = @category.articles.order('updated_at DESC').paginate(page: params[:page], per_page: 9)

  end

  def edit

    @category = Category.find(params[:id])

  end

  def update

    @category = Category.find(params[:id])

    if @category.update(category_params)

      flash[:success] = "Category name was successfully updated"

      redirect_to "/news/"+@category.name

    else

      render 'edit'

    end

  end
  private

  def category_params

    params.require(:category).permit(:name)

  end
  private
  def require_admin
    if current_user.admin != true
      flash[:danger]="You can view Categories only!!"
      redirect_to '/news'
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, "/news/"+category.name %> </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <div class="form-group">

    <div class="control-label col-sm-2">

      <%= f.label :name %>

    </div>

    <div class="col-sm-8">

      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>

    </div>

  </div>

  <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">

      <%= f.submit class: 'btn btn-primary btn-lg' %>

    </div>

  </div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<% if current_user.admin? %>
  <%= link_to "new category", new_category_path %>
  <% end %>

<div align="center">

  <%= will_paginate %>

  <% @categories.each do |category| %>

    <ul class="listing">

      <div class="row">

        <div class="well col-md-4 col-md-offset-4">

          <li class="article-title">

            <%= link_to "#{category.name}", "/news/"+category.name %>

          </li>

          <li><small><%= pluralize(category.articles.count, "article") %></small></li>

        </div>

      </div>

    </ul>

  <% end %>

  <%= will_paginate %>

</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<!doctype html>

<html>


<head>
  <!-- Meta Data -->
  <%= javascript_include_tag "validation.js" %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Z Online | <%= @category.name %></title>

  <!-- Fav Icon -->
  <link rel="apple-touch-icon" sizes="180x180" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="32x32" href="../assets/media/Z_ICO.ico">
  <link rel="icon" type="image/png" sizes="16x16" href="../assets/media/Z_ICO.ico">
  <meta name="theme-color" content="#3d0e03">

  <!-- Dependency Styles -->
  <link rel="stylesheet" href="../assets/dependencies/bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/brands.css" integrity="sha384-7xAnn7Zm3QC1jFjVc1A6v/toepoG3JXboQYzbM0jrPzou9OFXm/fY6Z/XiIebl/k" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">


  <!-- Site Stylesheet -->
  <link rel="stylesheet" href="../assets/dependencies/swiper/swiper.min.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/wow/css/animate.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/magnific-popup/magnific-popup.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-animated-headlines/css/jquery.animatedheadline.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/woocommerce.css" type="text/css">
  <link rel="stylesheet" href="../assets/dependencies/jquery-ui/css/jquery-ui.css" type="text/css">
  <link rel="stylesheet" href="../assets/home-dependencies/app.css" type="text/css">

  <!-- Google Web Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Khand:300,400,500,600,700%7C;Source+Sans+Pro:200,300,400,600,600i,700,900" rel="stylesheet">


</head>

<body class="blog-grid-three-column bgb" data-style="default">
<!--
<div id="loader-wrapper">
  <div class="loader">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </div>
</div> -->
<div id="loader-wrapper">
  <div class='loader'></div>
</div>

<div class="switch-top">
  <p>Back To Top</p>
  <a href="#main_content" data-type="section-switch" class="return-to-top">
    <i class="fa fa-angle-double-up"></i>
  </a>
</div>

<div id="main_content">


  <%= render "welcome/Navbar" %>


  <!--=========================-->
  <!--=        Banner         =-->
  <!--=========================-->
  <section id="page-header" data-bg-image="../assets/media/background/15.jpg">
    <div class="container">
      <div class="page-title-wrap">
        <div class="page-title-inner">
          <h1><%= @category.name %></h1>
          <h3>Game News</h3>
          <span class="delemitter" data-bg-image="../assets/media/banner/s1.png"></span>
        </div>
        <!-- /.page-title-inner -->
      </div>
      <!-- /.page-title-wrap -->
    </div>
    <!-- /.container -->
  </section>
  <!-- /#page-header -->

  <!--========================================-->
  <!--=        Z ONLINE NEWS                  =-->
  <!--========================================-->
  <section class="blog-masonry pt__50">
    <div class="container">

      <div class="row" style="min-height: 600px">

        <% @category_articles.each do |article| %>

          <div class="col-lg-4" style="padding-bottom: 15px;">
            <div class="clan-blog-post">
              <div class="feature-image">
                <a href="<%= article_path(article) %>">
                  <% if article.timage.present? %>
                    <img src="<%= article.timage  %>" alt="thamb">
                  <% else %>
                    <img src="../assets/media/Default.png" alt="thamb">
                  <% end %>
                </a>
              </div>

              <div class="content">
                <h3><a href="<%= article_path(article) %>"><%= article.title %></a></h3>

                <ul class="meta meta-grey">
                  <li><a href="#"><i class="fa fa-calendar"></i><%= article.updated_at %></a></li>
                  <li><a href="#" class="date"><i class="fa fa-commenting-o"></i><%= pluralize(article.comments.count,"Comment") %></a></li>
                </ul>

                <p>
                  <%= article.description[0...40] %> [...]
                </p>
              </div>
            </div>
          </div>
          <!-- /.col-lg-4 -->
        <% end %>

      </div>


      <nav class="navigation pagination float-right">
        <ul class="nav-links" id="pagination">
<!--          <li><a href="#"><i class="fa fa-angle-left"></i></a></li>-->
<!--          <li><a href="#">1</a></li>-->
<!--          <li><a href="#" class="active">2</a></li>-->
<!--          <li><a href="#">3</a></li>-->
<!--          <li><a href="#">4</a></li>-->
<!--          <li><a href="#">...</a></li>-->
<!--          <li><a href="#"><i class="fa fa-angle-right"></i></a></li>-->
          <%= will_paginate @category_articles, :container => false, :previous_label => '<-', :next_label => '->' %>
        </ul>
        <script>
            var ul = document.getElementById("pagination");
            var items = ul.getElementsByTagName("li");
            for (var i = 0; i < items.length; ++i) {
                items[i].childNodes[0].classList.remove("active");
                if (items[i].classList.contains("active"))
                {
                    items[i].childNodes[0].classList.add("active");
                }
            }
        </script>
      </nav>

      <%#= will_paginate @category_articles, class: "navigation pagination float-right" %>
      <div class="clearfix"></div>
      <div class="row" style="min-height: 100px ;">
      </div>

    </div>
    <!-- /.container -->
  </section>
  <!-- /.blog-masonry -->
  <%= render "welcome/Footer" %>
</div>
<!-- /#site -->

<!-- Dependency Scripts -->
<script src="../assets/dependencies/jquery/jquery.min.js"></script>
<script src="../assets/dependencies/bootstrap/js/bootstrap.min.js"></script>
<script src="../assets/dependencies/swiper/js/swiper.min.js"></script>
<script src="../assets/dependencies/swiperRunner/swiperRunner.min.js"></script>
<script src="../assets/dependencies/magnific-popup/js/jquery.magnific-popup.min.js"></script>
<script src="../assets/dependencies/jquery-ui/jquery-ui.min.js"></script>
<script src="../assets/dependencies/jquery-animated-headlines/js/jquery.animatedheadline.min.js"></script>
<script src="../assets/dependencies/jquery.countdown/jquery.countdown.min.js"></script>
<script src="../assets/dependencies/countUp.js/js/countUp.min.js"></script>
<script src="../assets/dependencies/jquery.appear.bas2k/jquery.appear.js"></script>
<script src="../assets/dependencies/jquery.ripples/jquery.ripples.js"></script>
<script src="../assets/dependencies/wow/js/wow.min.js"></script>

<!-- Site Scripts -->
<script src="../assets/home-dependencies/app.js"></script>

</body>

</html>